const challenges = [
  {
    number: 1,
    name: '운동하기',
    category: 'routine',
    type: 'individual',
    totalDays: 14,
    startDate: '2022.11.25',
    endDate: '',
    reward: '24시간 잠자기',
    passCount: 3,
    status: 'ongoing',
    dajimOpen: '',
    dajimContent: '',
  },
  {
    number: 2,
    name: '밥먹기',
    category: 'routine',
    type: 'group',
    totalDays: 30,
    startDate: '2022.11.25',
    endDate: '',
    reward: '아이패드',
    passCount: 4,
    status: 'success',
  },
  {
    number: 3,
    name: '잠자기',
    category: 'routine',
    type: 'individual',
    totalDays: 60,
    startDate: '2022.11.25',
    endDate: '',
    reward: '맥북 프로',
    passCount: 5,
    status: 'ongoing',
  },
  {
    number: 4,
    name: '여행가기',
    category: 'routine',
    type: 'group',
    totalDays: 14,
    startDate: '2022.11.25',
    endDate: '',
    reward: '애플워치',
    passCount: 2,
    status: 'fail',
  },
];

export default challenges;
